"""
01_persona_inspector.py — Persona Inspector page for the Trader Personas demo app.

Talk section: Section III — The Proposed Framework (fine-tuning framework)

Purpose:
    Allows users to browse pre-generated persona reasoning examples side by side.
    Loads from eval/results/persona_examples.json — a file generated by running:
        python data/generate_personas.py --export-examples

    The core demo moment: the same market state, three completely different
    conclusions. The side-by-side layout makes the divergence immediately legible
    to a non-technical audience.

Key design decisions:
    - All data is pre-loaded from JSON. No model inference happens at runtime.
    - The "Why they disagree" expander grounds each comparison in behavioral
      finance theory, bridging the gap between the LLM output and economic intuition.
    - Graceful handling of missing file: show st.info() with clear instructions.
"""

import json
from pathlib import Path

import streamlit as st

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

RESULTS_PATH = Path("eval/results/persona_examples.json")

PERSONA_COLORS = {
    "momentum": "#E8A838",  # amber
    "value": "#3A86FF",     # blue
    "noise": "#FF6B6B",     # coral
}

PERSONA_LABELS = {
    "momentum": "Momentum Trader",
    "value": "Value Investor",
    "noise": "Noise Trader",
}

ACTION_EMOJI = {
    "BUY": "BUY",
    "SELL": "SELL",
    "HOLD": "HOLD",
}

ACTION_COLORS = {
    "BUY": "#50FA7B",
    "SELL": "#FF6B6B",
    "HOLD": "#8BE9FD",
}

PERSONA_THEORY = {
    "momentum": (
        "**Jegadeesh & Titman (1993)**: Momentum traders believe recent price trends persist. "
        "They do not consider fundamental value — their only input is the direction and "
        "magnitude of recent price changes. In an uptrend, they buy regardless of whether "
        "the price is 'cheap' or 'expensive.'"
    ),
    "value": (
        "**Kahneman & Tversky; Shefrin & Statman**: Value investors anchor to an estimate "
        "of intrinsic value. They buy when the price falls below fair value (margin of safety) "
        "and sell when it rises above it. They are explicitly uninfluenced by short-term momentum — "
        "a rising price, to them, is a reason to be more cautious, not more optimistic."
    ),
    "noise": (
        "**De Long et al. (1990); Odean (1999)**: Noise traders react to news and perceived "
        "market sentiment. Their decisions are partially random and amplified by overconfidence. "
        "They tend to follow the crowd in trending markets and panic in declining ones, "
        "generating high turnover and sentiment-driven volatility."
    ),
}

DISAGREEMENT_EXPLANATIONS = {
    "Strong uptrend, bullish news": (
        "In a strong uptrend, the momentum trader buys because the trend is their signal. "
        "The value investor sells because the price has risen above fair value — the uptrend "
        "itself is a warning sign, not a green light. The noise trader buys enthusiastically, "
        "reacting to the positive news and following perceived market consensus. "
        "Three agents, same data, opposite conclusions — because they weight signals differently."
    ),
    "Strong downtrend, negative news": (
        "A falling price with bad news creates the maximum contrast between personas. "
        "The momentum trader sells to ride the trend. The value investor sees a buying "
        "opportunity: price has fallen below fair value, creating a margin of safety. "
        "The noise trader panics and sells, following the 'everyone is getting out' narrative. "
        "Value investors are the market's natural stabilizers — they buy exactly when others sell."
    ),
    "Price significantly below fair value": (
        "Without a strong trend, the momentum trader holds — there is no signal to follow. "
        "The value investor's opportunity has arrived: a significant discount to fair value "
        "justifies a buy with high conviction. The noise trader may buy tentatively, "
        "partly random and perhaps reacting to low prices as a vague 'opportunity,' "
        "but without the fundamental conviction of the value investor."
    ),
    "Price significantly above fair value": (
        "A price well above fair value is the value investor's clearest sell signal. "
        "The momentum trader may continue buying if the uptrend holds — the premium to "
        "fair value is irrelevant to them. The noise trader may buy on overconfidence, "
        "chasing the move. This is the moment when value investors provide negative feedback "
        "against speculative excess."
    ),
    "default": (
        "Each persona weights market signals differently based on its underlying theory. "
        "Momentum traders prioritize price direction. Value investors prioritize deviation "
        "from fundamental value. Noise traders react to sentiment and news. "
        "In most market states, at least two of the three will disagree — "
        "and this disagreement is precisely what generates realistic market dynamics."
    ),
}

# ---------------------------------------------------------------------------
# Page setup
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Persona Inspector | Trader Personas",
    layout="centered",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------


@st.cache_data
def load_examples() -> list[dict] | None:
    """
    Load persona comparison examples from JSON.

    Args:
        None (reads from RESULTS_PATH).

    Returns:
        A list of scenario dicts, or None if the file does not exist.

    Why this matters:
        Caching the file load avoids re-reading disk on every Streamlit interaction.
    """
    if not RESULTS_PATH.exists():
        return None
    with open(RESULTS_PATH, "r") as f:
        return json.load(f)


examples = load_examples()

# ---------------------------------------------------------------------------
# Handle missing data
# ---------------------------------------------------------------------------

if examples is None:
    st.title("Persona Inspector")
    st.info(
        "**Results file not found.**\n\n"
        "To populate this page, generate the persona comparison examples:\n\n"
        "```bash\nexport ANTHROPIC_API_KEY=your_key_here\n"
        "python data/generate_personas.py --export-examples\n```\n\n"
        f"Expected file: `{RESULTS_PATH}`"
    )
    st.stop()

# ---------------------------------------------------------------------------
# Sidebar controls
# ---------------------------------------------------------------------------

with st.sidebar:
    st.markdown("## Persona Inspector")
    st.markdown("*Section III — Fine-tuning framework*")
    st.divider()

    # Scenario selector
    scenario_labels = [ex["label"] for ex in examples]
    selected_label = st.selectbox(
        "Select scenario",
        scenario_labels,
        index=0,
        help="Choose a market scenario to explore. All three personas will respond to the same inputs.",
    )

    st.divider()

    # Persona filter
    st.markdown("**Show personas:**")
    show_momentum = st.checkbox("Momentum Trader", value=True)
    show_value = st.checkbox("Value Investor", value=True)
    show_noise = st.checkbox("Noise Trader", value=True)

    visible_personas = []
    if show_momentum:
        visible_personas.append("momentum")
    if show_value:
        visible_personas.append("value")
    if show_noise:
        visible_personas.append("noise")

    st.divider()
    st.markdown(
        """
        *Each scenario uses the same market state for all three personas.
        Differences in reasoning and action are purely due to persona type.*
        """
    )

# ---------------------------------------------------------------------------
# Find selected scenario
# ---------------------------------------------------------------------------

selected_scenario = next((ex for ex in examples if ex["label"] == selected_label), examples[0])

# ---------------------------------------------------------------------------
# Main panel
# ---------------------------------------------------------------------------

st.title("Persona Inspector")
st.markdown(
    f"**Scenario**: {selected_scenario['label']}"
)
if selected_scenario.get("description"):
    st.caption(selected_scenario["description"])

# Market state display
market_state = selected_scenario["market_state"]
with st.expander("Market State (same for all personas)", expanded=True):
    ms_col1, ms_col2, ms_col3 = st.columns(3)
    with ms_col1:
        st.metric("Current Price", f"{market_state['price_history'][-1]:.2f}")
        st.metric("Fair Value", f"{market_state['fair_value']:.2f}")
    with ms_col2:
        price_change = (
            (market_state["price_history"][-1] - market_state["price_history"][0])
            / market_state["price_history"][0]
            * 100
        )
        st.metric("Price Change (5-period)", f"{price_change:+.2f}%")
        st.metric("Price / Fair Value", f"{market_state['price_history'][-1] / market_state['fair_value']:.3f}")
    with ms_col3:
        st.markdown("**Price History:**")
        st.code(str(market_state["price_history"]))
    st.markdown(f"**News:** {market_state['news']}")

st.divider()

# ---------------------------------------------------------------------------
# Persona cards
# ---------------------------------------------------------------------------

if not visible_personas:
    st.warning("No personas selected. Use the sidebar checkboxes to show at least one persona.")
    st.stop()

columns = st.columns(len(visible_personas))

for col, persona in zip(columns, visible_personas):
    persona_data = selected_scenario.get("personas", {}).get(persona, {})
    reasoning = persona_data.get("reasoning", "No data available.")
    action = persona_data.get("action", "HOLD")
    quantity = persona_data.get("quantity", 0)
    color = PERSONA_COLORS[persona]
    label = PERSONA_LABELS[persona]
    action_color = ACTION_COLORS.get(action, "#FFFFFF")

    with col:
        # Persona name badge
        st.markdown(
            f'<div style="background-color: {color}22; border: 1.5px solid {color}; '
            f'border-radius: 6px; padding: 6px 12px; margin-bottom: 10px;">'
            f'<span style="color: {color}; font-weight: bold; font-size: 15px;">{label}</span>'
            f"</div>",
            unsafe_allow_html=True,
        )

        # Reasoning chain
        st.markdown("**Reasoning:**")
        st.markdown(
            f'<div style="background-color: #1A1F2E; border-left: 3px solid {color}; '
            f'padding: 10px 14px; border-radius: 4px; font-size: 13px; '
            f'line-height: 1.5; color: #FAFAFA; min-height: 100px;">'
            f"{reasoning}"
            f"</div>",
            unsafe_allow_html=True,
        )

        st.markdown("<br>", unsafe_allow_html=True)

        # Action callout
        display_action = action if quantity == 0 or action == "HOLD" else f"{action} {quantity} shares"
        st.markdown(
            f'<div style="background-color: {action_color}22; border: 2px solid {action_color}; '
            f'border-radius: 6px; padding: 10px 14px; text-align: center;">'
            f'<span style="color: {action_color}; font-weight: bold; font-size: 18px;">'
            f"{display_action}</span>"
            f"</div>",
            unsafe_allow_html=True,
        )

        # Theory grounding (collapsed)
        with st.expander(f"About {label}"):
            st.markdown(PERSONA_THEORY[persona])

# ---------------------------------------------------------------------------
# "Why they disagree" expander
# ---------------------------------------------------------------------------

st.divider()

with st.expander("Why They Disagree — Behavioral Finance Theory", expanded=False):
    explanation = DISAGREEMENT_EXPLANATIONS.get(
        selected_label, DISAGREEMENT_EXPLANATIONS["default"]
    )
    st.markdown(explanation)

    st.divider()

    if len(visible_personas) >= 2:
        actions = {
            p: selected_scenario.get("personas", {}).get(p, {}).get("action", "HOLD")
            for p in visible_personas
        }
        action_set = set(actions.values())
        if len(action_set) == 1:
            st.success(
                f"All visible personas agree: **{list(action_set)[0]}**. "
                "This is a relatively rare consensus scenario."
            )
        else:
            disagreements = []
            for p in visible_personas:
                a = actions[p]
                disagreements.append(f"{PERSONA_LABELS[p]}: **{a}**")
            st.info("Decision summary: " + " | ".join(disagreements))
