"""
02_run_simulation.py — Simulation Explorer page for the Trader Personas demo app.

Talk section: Section III — The Proposed Framework (simulation framework)

Purpose:
    Allows users to explore pre-computed simulation runs across different persona
    compositions. Loads from eval/results/simulations/ — a directory of JSON files
    generated by:
        python simulation/run_simulation.py --precompute

    Shows three interactive Plotly charts:
    1. Price series over time
    2. Per-tick order flow breakdown (buys vs sells by persona)
    3. Agent P&L at end of simulation grouped by persona

Key design decisions:
    - All data is pre-loaded from JSON. No model inference or simulation at runtime.
    - Uses Plotly for all charts (interactive, better for live demos than matplotlib).
    - "What drove this market?" expander surfaces key moments from the simulation log.
    - Graceful handling of missing directory with clear st.info() instructions.
"""

import json
from pathlib import Path

import plotly.graph_objects as go
import plotly.express as px
import streamlit as st

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SIMULATIONS_DIR = Path("eval/results/simulations")

PERSONA_COLORS = {
    "momentum": "#E8A838",
    "value": "#3A86FF",
    "noise": "#FF6B6B",
}

PERSONA_LABELS = {
    "momentum": "Momentum",
    "value": "Value",
    "noise": "Noise",
}

# ---------------------------------------------------------------------------
# Page setup
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Simulation Explorer | Trader Personas",
    layout="centered",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------


@st.cache_data
def load_simulation_files() -> dict[str, dict]:
    """
    Load all pre-computed simulation JSON files from the simulations directory.

    Args:
        None (reads from SIMULATIONS_DIR).

    Returns:
        A dict mapping filename (without extension) -> simulation data dict.
        Returns an empty dict if the directory is missing or empty.

    Why this matters:
        Caching prevents re-reading all files on every user interaction, which
        is important when files can be up to a few MB each.
    """
    if not SIMULATIONS_DIR.exists():
        return {}

    simulations = {}
    for json_file in sorted(SIMULATIONS_DIR.glob("*.json")):
        with open(json_file, "r") as f:
            data = json.load(f)
        simulations[json_file.stem] = data

    return simulations


simulations = load_simulation_files()

# ---------------------------------------------------------------------------
# Handle missing data
# ---------------------------------------------------------------------------

if not simulations:
    st.title("Simulation Explorer")
    st.info(
        "**No simulation results found.**\n\n"
        "To populate this page, pre-compute the simulation library:\n\n"
        "```bash\npython simulation/run_simulation.py --precompute\n```\n\n"
        f"Expected directory: `{SIMULATIONS_DIR}`"
    )
    st.stop()

# ---------------------------------------------------------------------------
# Sidebar controls
# ---------------------------------------------------------------------------

with st.sidebar:
    st.markdown("## Simulation Explorer")
    st.markdown("*Section III — Simulation framework*")
    st.divider()

    # Build display labels from the simulation data names.
    sim_display_names = {}
    for key, data in simulations.items():
        sim_display_names[key] = data.get("name", key)

    selected_key = st.selectbox(
        "Select simulation run",
        list(sim_display_names.keys()),
        format_func=lambda k: sim_display_names[k],
        help="Choose a pre-computed simulation run to explore.",
    )

    st.divider()

    st.markdown("**Show charts:**")
    show_price = st.checkbox("Price Series", value=True)
    show_order_flow = st.checkbox("Order Flow", value=True)
    show_pnl = st.checkbox("Agent P&L", value=True)

    st.divider()
    st.markdown(
        """
        *All data is pre-computed. No live inference runs in this app.*
        """
    )

# ---------------------------------------------------------------------------
# Load selected simulation
# ---------------------------------------------------------------------------

sim_data = simulations[selected_key]
price_series = sim_data["price_series"]
order_flow = sim_data.get("order_flow", [])
agent_pnl = sim_data.get("agent_pnl", {})
agent_personas = sim_data.get("agent_personas", {})
persona_composition = sim_data.get("persona_composition", {})
market_summary = sim_data.get("market_summary", {})
metadata = sim_data.get("metadata", {})

# ---------------------------------------------------------------------------
# Main panel
# ---------------------------------------------------------------------------

st.title("Simulation Explorer")
st.markdown(f"**Run**: {sim_data.get('name', selected_key)}")

# Summary metrics row
summary_col1, summary_col2, summary_col3, summary_col4 = st.columns(4)
with summary_col1:
    st.metric("Initial Price", f"{market_summary.get('initial_price', 100):.2f}")
with summary_col2:
    final = market_summary.get("final_price", price_series[-1] if price_series else 0)
    initial = market_summary.get("initial_price", 100)
    delta_pct = (final - initial) / max(initial, 0.01) * 100
    st.metric("Final Price", f"{final:.2f}", delta=f"{delta_pct:+.1f}%")
with summary_col3:
    st.metric("Ticks", str(metadata.get("n_ticks", len(price_series) - 1)))
with summary_col4:
    st.metric("Agents", str(metadata.get("n_agents", len(agent_pnl))))

# Persona composition badges
st.markdown("**Composition:**")
comp_cols = st.columns(len(persona_composition))
for col, (persona, count) in zip(comp_cols, persona_composition.items()):
    color = PERSONA_COLORS.get(persona, "#888")
    label = PERSONA_LABELS.get(persona, persona.capitalize())
    with col:
        st.markdown(
            f'<div style="background-color: {color}22; border: 1px solid {color}; '
            f'border-radius: 4px; padding: 4px 10px; text-align: center;">'
            f'<span style="color: {color}; font-weight: bold;">{count} {label}</span>'
            f"</div>",
            unsafe_allow_html=True,
        )

st.divider()

# ---------------------------------------------------------------------------
# Chart 1: Price Series
# ---------------------------------------------------------------------------

if show_price and price_series:
    st.markdown("### Price Series")

    ticks = list(range(len(price_series)))

    # Color each tick by the dominant order flow persona.
    # We compute dominant persona per tick from the order flow data.
    tick_dominant_persona = []
    for tick_flow in order_flow:
        persona_vols = tick_flow.get("persona_volumes", {})
        # Find persona with highest net buy volume.
        best_persona = "noise"  # default
        best_net = -1e9
        for persona, vols in persona_vols.items():
            net = vols.get("buy", 0) - vols.get("sell", 0)
            if net > best_net:
                best_net = net
                best_persona = persona
        tick_dominant_persona.append(best_persona)

    fig_price = go.Figure()

    # Main price line.
    fig_price.add_trace(
        go.Scatter(
            x=ticks,
            y=price_series,
            mode="lines",
            name="Price",
            line=dict(color="#FAFAFA", width=1.2),
        )
    )

    # Initial price reference line.
    fig_price.add_hline(
        y=price_series[0],
        line_dash="dot",
        line_color="#888888",
        opacity=0.5,
        annotation_text="Initial",
        annotation_position="right",
    )

    fig_price.update_layout(
        title="Price Over Time",
        xaxis_title="Tick",
        yaxis_title="Price",
        plot_bgcolor="#1A1F2E",
        paper_bgcolor="#0E1117",
        font=dict(color="#FAFAFA"),
        height=300,
        margin=dict(l=50, r=20, t=40, b=40),
        showlegend=False,
    )

    st.plotly_chart(fig_price, use_container_width=True)

# ---------------------------------------------------------------------------
# Chart 2: Order Flow
# ---------------------------------------------------------------------------

if show_order_flow and order_flow:
    st.markdown("### Per-Tick Order Flow")

    ticks = list(range(len(order_flow)))

    # Build buy and sell series per persona.
    persona_buy: dict[str, list[int]] = {}
    persona_sell: dict[str, list[int]] = {}

    active_personas = list(persona_composition.keys())

    for persona in active_personas:
        persona_buy[persona] = []
        persona_sell[persona] = []

    for tick_flow in order_flow:
        persona_vols = tick_flow.get("persona_volumes", {})
        for persona in active_personas:
            vols = persona_vols.get(persona, {"buy": 0, "sell": 0})
            persona_buy[persona].append(vols.get("buy", 0))
            persona_sell[persona].append(-vols.get("sell", 0))  # Negative for sells

    fig_flow = go.Figure()

    for persona in active_personas:
        color = PERSONA_COLORS.get(persona, "#888")
        label = PERSONA_LABELS.get(persona, persona.capitalize())

        fig_flow.add_trace(
            go.Bar(
                x=ticks,
                y=persona_buy[persona],
                name=f"{label} Buy",
                marker_color=color,
                opacity=0.7,
            )
        )
        fig_flow.add_trace(
            go.Bar(
                x=ticks,
                y=persona_sell[persona],
                name=f"{label} Sell",
                marker_color=color,
                opacity=0.4,
            )
        )

    fig_flow.add_hline(y=0, line_color="#888888", line_width=0.5)

    fig_flow.update_layout(
        title="Buy (positive) / Sell (negative) Volume by Persona",
        xaxis_title="Tick",
        yaxis_title="Volume",
        barmode="relative",
        plot_bgcolor="#1A1F2E",
        paper_bgcolor="#0E1117",
        font=dict(color="#FAFAFA"),
        height=300,
        margin=dict(l=50, r=20, t=40, b=40),
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1,
            font=dict(size=10),
        ),
    )

    st.plotly_chart(fig_flow, use_container_width=True)

# ---------------------------------------------------------------------------
# Chart 3: Agent P&L
# ---------------------------------------------------------------------------

if show_pnl and agent_pnl:
    st.markdown("### Final Agent P&L by Persona")

    # Group agents by persona for the chart.
    persona_pnl_lists: dict[str, list[float]] = {}
    persona_agent_labels: dict[str, list[str]] = {}

    for agent_id, pnl in agent_pnl.items():
        persona = agent_personas.get(agent_id, "unknown")
        if persona not in persona_pnl_lists:
            persona_pnl_lists[persona] = []
            persona_agent_labels[persona] = []
        persona_pnl_lists[persona].append(pnl)
        persona_agent_labels[persona].append(agent_id)

    fig_pnl = go.Figure()

    for persona in persona_composition.keys():
        if persona not in persona_pnl_lists:
            continue
        color = PERSONA_COLORS.get(persona, "#888")
        label = PERSONA_LABELS.get(persona, persona.capitalize())
        pnl_values = persona_pnl_lists[persona]
        agent_labels = persona_agent_labels[persona]

        fig_pnl.add_trace(
            go.Bar(
                x=agent_labels,
                y=pnl_values,
                name=label,
                marker_color=color,
                opacity=0.8,
            )
        )

    fig_pnl.add_hline(y=0, line_color="#888888", line_dash="dot", line_width=1)

    fig_pnl.update_layout(
        title="Final P&L per Agent (grouped by persona)",
        xaxis_title="Agent",
        yaxis_title="P&L (USD)",
        plot_bgcolor="#1A1F2E",
        paper_bgcolor="#0E1117",
        font=dict(color="#FAFAFA"),
        height=350,
        margin=dict(l=50, r=20, t=40, b=60),
        xaxis=dict(showticklabels=False),
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1,
        ),
    )

    st.plotly_chart(fig_pnl, use_container_width=True)

    # P&L summary by persona
    st.markdown("**P&L Summary by Persona:**")
    pnl_summary_cols = st.columns(len(persona_pnl_lists))
    for col, (persona, pnl_values) in zip(pnl_summary_cols, persona_pnl_lists.items()):
        label = PERSONA_LABELS.get(persona, persona.capitalize())
        mean_pnl = sum(pnl_values) / len(pnl_values) if pnl_values else 0.0
        color = PERSONA_COLORS.get(persona, "#888")
        with col:
            st.markdown(
                f'<div style="background-color: {color}22; border: 1px solid {color}; '
                f'border-radius: 4px; padding: 8px 10px; text-align: center;">'
                f'<span style="color: {color}; font-weight: bold;">{label}</span><br>'
                f'<span style="color: #FAFAFA; font-size: 16px;">Avg: {mean_pnl:+.2f}</span>'
                f"</div>",
                unsafe_allow_html=True,
            )

# ---------------------------------------------------------------------------
# "What drove this market?" expander
# ---------------------------------------------------------------------------

st.divider()

with st.expander("What drove this market?", expanded=False):
    if order_flow:
        # Find the largest single-tick price move.
        max_move = 0.0
        max_move_tick = 0
        for i in range(1, len(price_series)):
            move = abs(price_series[i] - price_series[i - 1])
            if move > max_move:
                max_move = move
                max_move_tick = i

        max_move_pct = max_move / max(price_series[max_move_tick - 1], 0.01) * 100
        direction = "up" if price_series[max_move_tick] > price_series[max_move_tick - 1] else "down"

        st.markdown(
            f"**Largest single-tick move**: Tick {max_move_tick} — price moved "
            f"{direction} by {max_move_pct:.3f}% ({max_move:.4f} points)."
        )

        if max_move_tick <= len(order_flow):
            tick_flow = order_flow[max_move_tick - 1]
            imbalance = tick_flow.get("order_imbalance", 0.0)
            buy_vol = tick_flow.get("buy_volume", 0)
            sell_vol = tick_flow.get("sell_volume", 0)

            st.markdown(
                f"At tick {max_move_tick}: "
                f"buy volume = {buy_vol}, sell volume = {sell_vol}, "
                f"order imbalance = {imbalance:.3f}."
            )

            # Which persona contributed most to the imbalance?
            persona_vols = tick_flow.get("persona_volumes", {})
            if persona_vols:
                persona_net = {
                    p: v.get("buy", 0) - v.get("sell", 0)
                    for p, v in persona_vols.items()
                }
                dominant = max(persona_net, key=lambda p: abs(persona_net[p]))
                net_val = persona_net[dominant]
                st.markdown(
                    f"**Dominant persona**: {PERSONA_LABELS.get(dominant, dominant)} "
                    f"(net volume: {net_val:+d} shares)."
                )

    # Overall narrative
    final_price = market_summary.get("final_price", price_series[-1] if price_series else 0)
    initial_price = market_summary.get("initial_price", 100)
    total_return = (final_price - initial_price) / max(initial_price, 0.01) * 100

    composition_str = ", ".join(
        f"{count} {PERSONA_LABELS.get(p, p)}" for p, count in persona_composition.items()
    )

    st.markdown(
        f"**Summary**: A population of {composition_str} ran for "
        f"{metadata.get('n_ticks', '?')} ticks. "
        f"The market moved {total_return:+.2f}% overall "
        f"({'rising' if total_return >= 0 else 'falling'} from "
        f"{initial_price:.2f} to {final_price:.2f})."
    )
